


# This task configures /etc/network/interfaces on ifupdown2. The variables for
# which interfaces are neighbors and networks come from the group_vars/all file.
- name: configure networking
  nclu:
      atomic: true
      description: "configure all the newtorking"
      template: |
           {% for i in range(count) %}
           add int swp1 bridge access {{10+i}}
           {% endfor %}
