


- name: configure networking
  command: "net abort"


# This task configures /etc/network/interfaces on ifupdown2. The variables for
# which interfaces are neighbors and networks come from the group_vars/all file.
- name: configure networking
  command: "net {{ item }}"
  with_items: "{{ range(10+(count|int)) }}"

- name: configure networking
  command: "net commit"
